language: node_js
sudo: false

node_js:
  - 8
  - 7
  - 6

cache:
  yarn: true
  directories:
    - ~/.npm
    - node_modules

branches:
  only:
    - master

before_install:
  - "curl -o- -L https://yarnpkg.com/install.sh | bash"
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

script:
  - yarn test

deploy:
  provider: script
  script: yarn travis-deploy-once "yarn semantic-release"
  skip_cleanup: true
  on:
    branch: master
